services:
  php:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - node

  node:
    build:
      context: ./node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3305:3305"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autocasion
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssw0rd

  adminer:
    image: adminer
    ports:
      - "8085:8080"
